### ISSUE TITLE
Do you know how we can proxy RestFul web service (Spring MVC) in WSO2 API manager? And how we can call it through RestTemplate etc?

### ISSUE THREAD

**Issue by ghost** [ihcsim/docker-wso2apim#2]
Do you know how we can proxy RestFul web service (Spring MVC) in WSO2 API manager? And how we can call it through RestTemplate etc?

**Comment by ihcsim** [comment]
Sorry, I am unfamiliar with this. If you already have a Spring MVC application with web services exposed, you might just want to deploy it to the Application Server as your "backend", and create and publish separate APIs in the API Publisher and Store pointing to your web services. Take a look at this WSO2 [sample](https://docs.wso2.com/display/AM170/Invoking+APIs+using+a+Web+App+Deployed+in+WSO2+AS) to see if it helps.
