### ISSUE TITLE
Can you please specify the volume to be mounted from the container end?

### ISSUE THREAD

**Issue by Arun-Trichy** [ihcsim/docker-wso2apim#6]

**Comment by jkroepke** [comment]
It should be /opt/wso2am-2.0.0/repository/database/

**Comment by ihcsim** [comment]
Sorry for the late reply. Somehow, GH didn't notify me of this issue. I have updated the Dockerfile with the `VOLUME` directive.

Refer to the WSO2 [docs](https://wso2.com/api-management/install/docker/get-started/) for the official APIM Docker image.
