### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by gb8may** [ihcsim/docker-wso2apim#8]
Can you please update API Manager to version 2.1.0?

**Comment by ihcsim** [comment]
I have updated the Dockerfile to pull the 2.1.0 binary from my S3 bucket.

Refer the official WSO2 [docs](https://wso2.com/api-management/install/docker/get-started/) to get the official APIM Docker image.

**Comment by gb8may** [comment]
Perfect!

I’ll test it tomorrow....

Thank you.

Mayara Gouveia
Jr DevOps Engineer
Information Security Specialist
DevOps Professional | Agil Scrum Foundation CompTIA Network+ | Ethical Hacking Foundation | Fortinet NSE1
DCS Furukawa & Fluke Networks
Linux User #566363 | LPI ID: LPI000348552 Puppet ID: PPT0005371
